INSERT INTO team(team_id, nombre, pais, deleted, liga)
VALUES(1, 'Real Madrid', 'España', false, 'La Liga'),
      (2, 'FC Barcelona', 'España', false, 'La Liga'),
      (3, 'Manchester United', 'Inglaterra', false, 'Premier League'),
      (4, 'Liverpool FC', 'Inglaterra', false, 'Premier League'),
      (5, 'Juventus FC', 'Italia', false, 'Serie A'),
      (6, 'AC Milan', 'Italia', false, 'Serie A'),
      (7, 'Bayern Munich', 'Alemania', false, 'Bundesliga'),
      (8, 'Borussia Dortmund', 'Alemania', false, 'Bundesliga'),
      (9, 'Paris Saint-Germain', 'Francia', false, 'Ligue 1'),
      (10, 'Olympique de Marseille', 'Francia', false, 'Ligue 1'),
      (11, 'FC Porto', 'Portugal', false, 'Primeira Liga'),
      (12, 'Sporting CP', 'Portugal', false, 'Primeira Liga'),
      (13, 'Ajax Amsterdam', 'Países Bajos', false, 'Eredivisie'),
      (14, 'Feyenoord', 'Países Bajos', false, 'Eredivisie'),
      (15, 'Celtic FC', 'Escocia', false, 'Scottish Premiership'),
      (16, 'Rangers FC', 'Escocia', false, 'Scottish Premiership'),
      (17, 'Galatasaray SK', 'Turquía', false, 'Süper Lig'),
      (18, 'Fenerbahçe SK', 'Turquía', false, 'Süper Lig'),
      (19, 'FC Zenit Saint Petersburg', 'Rusia', false, 'Premier League Rusa'),
      (20, 'Spartak Moscow', 'Rusia', false, 'Premier League Rusa'),
      (21, 'SL Benfica', 'Portugal', false, 'Primeira Liga'),
      (22, 'Besiktas JK', 'Turquía', false, 'Süper Lig'),
      (23, 'SSC Napoli', 'Italia', false, 'Serie A'),
      (24, 'Atlético Madrid', 'España', false, 'La Liga');
ALTER SEQUENCE team_seq RESTART WITH 25;